apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #   service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
